Bigon.WebUI/Areas/Admin/Controllers/BrandsController.cs
using Bigon.Business.Modules.BrandsModule.Commands.BrandAddCommand;
using Bigon.Business.Modules.BrandsModule.Commands.BrandEditCommand;
using Bigon.Business.Modules.BrandsModule.Commands.BrandRemoveCommand;
using Bigon.Business.Modules.BrandsModule.Queries.BrandGetAllQuery;
using Bigon.Business.Modules.BrandsModule.Queries.BrandGetByIdQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandsController : Controller
    {
        private readonly IMediator mediator;
        public BrandsController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [Authorize("admin.brands.index")]
        public async Task<IActionResult> Index(BrandGetAllRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.brands.details")]
        public async Task<IActionResult> Details(BrandGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }


        [Authorize("admin.brands.create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize("admin.brands.create")]
        public async Task<IActionResult> Create(BrandAddRequest model)
        {
            await mediator.Send(model);
            return RedirectToAction(nameof(Index));
        }

        [Authorize("admin.brands.edit")]
        public async Task<IActionResult> Edit(BrandGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        [Authorize("admin.brands.edit")]
        public async Task<IActionResult> Edit(BrandEditRequest request)
        {
            await mediator.Send(request);
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        [Authorize("admin.brands.delete")]
        public async Task<IActionResult> Delete(BrandRemoveRequest request)
        {
            await mediator.Send(request);
            //var model = db.Brands.FirstOrDefault(m => m.Id == id && m.DeletedBy == null);

            //if (model == null)
            //{
            //    Response.Headers.Add("error", "true");

            //    string text = HttpUtility.UrlEncode("Qeyd mövcud deyil!");

            //    Response.Headers.Add("message", text);
            //    return Content("");
            //}

            //db.Brands.Remove(model);

            //db.SaveChanges();

            //var brands = db.Brands
            //    .Where(m => m.DeletedBy == null)
            //    .ToList();

            var response = await mediator.Send(new BrandGetAllRequest());

            //return View(brands);
            return PartialView("_Body", response);
        }
    }
}

Bigon.WebUI/Areas/Admin/Controllers/ColorsController.cs
using Bigon.Business.Modules.ColorsModule.Commands.ColorAddCommand;
using Bigon.Business.Modules.ColorsModule.Commands.ColorEditCommand;
using Bigon.Business.Modules.ColorsModule.Commands.ColorRemoveCommand;
using Bigon.Business.Modules.ColorsModule.Queries.ColorGetAllQuery;
using Bigon.Business.Modules.ColorsModule.Queries.ColorGetByIdQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ColorsController : Controller
    {
        private readonly IMediator mediator;
        public ColorsController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [Authorize("admin.colors.index")]
        public async Task<IActionResult> Index(ColorGetAllRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.colors.details")]
        public async Task<IActionResult> Details(ColorGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.colors.create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize("admin.colors.create")]
        public async Task<IActionResult> Create(ColorAddRequest request)
        {
            await mediator.Send(request);

            return RedirectToAction(nameof(Index));
        }

        [Authorize("admin.colors.edit")]
        public async Task<IActionResult> Edit(ColorGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        [Authorize("admin.colors.edit")]
        public async Task<IActionResult> Edit(ColorEditRequest request)
        {
            await mediator.Send(request);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        [Authorize("admin.colors.delete")]
        public async Task<IActionResult> Delete(ColorRemoveRequest request)
        {
            await mediator.Send(request);

            return Json(new
            {
                error = false,
                message = "Qeyd silindi!"
            });
        }
    }
}

Bigon.WebUI/Areas/Admin/Controllers/FaqsController.cs
using Bigon.Business.Modules.FaqsModule.Commands.FaqAddCommand;
using Bigon.Business.Modules.FaqsModule.Commands.FaqEditCommand;
using Bigon.Business.Modules.FaqsModule.Commands.FaqRemoveCommand;
using Bigon.Business.Modules.FaqsModule.Queries.FaqGetAllQuery;
using Bigon.Business.Modules.FaqsModule.Queries.FaqGetByIdQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FaqsController : Controller
    {
        private readonly IMediator mediator;
        public FaqsController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [Authorize("admin.faqs.index")]
        public async Task<IActionResult> Index(FaqGetAllRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.faqs.details")]
        public async Task<IActionResult> Details(FaqGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.faqs.create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize("admin.faqs.create")]
        public async Task<IActionResult> Create(FaqAddRequest request)
        {
            await mediator.Send(request);

            return RedirectToAction(nameof(Index));
        }

        [Authorize("admin.faqs.edit")]
        public async Task<IActionResult> Edit(FaqGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        [Authorize("admin.faqs.edit")]
        public async Task<IActionResult> Edit(FaqEditRequest request)
        {
            await mediator.Send(request);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        [Authorize("admin.faqs.delete")]
        public async Task<IActionResult> Delete(FaqRemoveRequest request)
        {
            await mediator.Send(request);

            return Json(new
            {
                error = false,
                message = "Qeyd silindi!"
            });
        }
    }
}

Bigon.WebUI/Areas/Admin/Controllers/SizesController.cs
using Bigon.Business.Modules.SizesModule.Commands.SizeAddCommand;
using Bigon.Business.Modules.SizesModule.Commands.SizeEditCommand;
using Bigon.Business.Modules.SizesModule.Commands.SizeRemoveCommand;
using Bigon.Business.Modules.SizesModule.Queries.SizeGetAllQuery;
using Bigon.Business.Modules.SizesModule.Queries.SizeGetByIdQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SizesController : Controller
    {
        private readonly IMediator mediator;
        public SizesController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [Authorize("admin.sizes.index")]
        public async Task<IActionResult> Index(SizeGetAllRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.sizes.details")]
        public async Task<IActionResult> Details(SizeGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [Authorize("admin.sizes.create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize("admin.sizes.create")]
        public async Task<IActionResult> Create(SizeAddRequest request)
        {
            await mediator.Send(request);

            return RedirectToAction(nameof(Index));
        }

        [Authorize("admin.sizes.edit")]
        public async Task<IActionResult> Edit(SizeGetByIdRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        [Authorize("admin.sizes.edit")]
        public async Task<IActionResult> Edit(SizeEditRequest request)
        {
            await mediator.Send(request);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        [Authorize("admin.sizes.delete")]
        public async Task<IActionResult> Delete(SizeRemoveRequest request)
        {
            await mediator.Send(request);

            return Json(new
            {
                error = false,
                message = "Qeyd silindi!"
            });
        }
    }
}

Bigon.WebUI/Areas/Admin/Views/Shared/_Preloader.cshtml
 <!-- Pre-loader start -->
<div class="theme-loader">
    <div class="ball-scale">
        <div class='contain'>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
        </div>
    </div>
</div>
<!-- Pre-loader end -->

Bigon.WebUI/Areas/Admin/Views/Shared/_Sidebar.cshtml
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">Main</div>
        <ul class="pcoded-item pcoded-left-item">
            @if (User.HasClaim("admin.dashboard.index"))
            {
                <li>
                    <a asp-controller="Dashboard" asp-action="Index">
                        <span class="pcoded-micon">
                            <i class="feather icon-home"></i>
                        </span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>
            }
            @if (User.HasClaim("admin.faqs.index"))
            {
                <li>
                    <a asp-controller="Faqs" asp-action="Index">
                        <span class="pcoded-micon">
                            <i class="feather icon-menu"></i>
                        </span>
                        <span class="pcoded-mtext">Faqs</span>
                    </a>
                </li>
            }
            @if (User.HasClaim("admin.blogs.index"))
            {
                <li>
                    <a asp-controller="BlogPosts" asp-action="Index">
                        <span class="pcoded-micon">
                            <i class="feather icon-menu"></i>
                        </span>
                        <span class="pcoded-mtext">BlogPosts</span>
                    </a>
                </li>
            }

            @if (User.HasClaim("admin.products.index"))
            {
                <li>
                    <a asp-controller="Products" asp-action="Index">
                        <span class="pcoded-micon">
                            <i class="feather icon-menu"></i>
                        </span>
                        <span class="pcoded-mtext">Products</span>
                    </a>
                </li>
            }

            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon">
                        <i class="feather icon-menu"></i>
                    </span>
                    <span class="pcoded-mtext">Lists</span>
                </a>
                <ul class="pcoded-submenu">

                    @if (User.HasClaim("admin.categories.index"))
                    {
                        <li>
                            <a asp-controller="Categories" asp-action="Index">
                                <span class="pcoded-mtext">Categories</span>
                            </a>
                        </li>
                    }
                    @if (User.HasClaim("admin.colors.index"))
                    {
                        <li>
                            <a asp-controller="Colors" asp-action="Index">
                                <span class="pcoded-mtext">Colors</span>
                            </a>
                        </li>
                    }
                    @if (User.HasClaim("admin.brands.index"))
                    {
                        <li>
                            <a asp-controller="Brands" asp-action="Index">
                                <span class="pcoded-mtext">Brands</span>
                            </a>
                        </li>
                    }
                    @if (User.HasClaim("admin.sizes.index"))
                    {
                        <li>
                            <a asp-controller="Sizes" asp-action="Index">
                                <span class="pcoded-mtext">Sizes</span>
                            </a>
                        </li>
                    }
                    @if (User.HasClaim("admin.materials.index"))
                    {
                        <li>
                            <a asp-controller="Materials" asp-action="Index">
                                <span class="pcoded-mtext">Materials</span>
                            </a>
                        </li>
                    }

                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">Settings</div>
        <ul>
            @if (User.HasClaim("admin.users.index"))
            {
                <li>
                    <a asp-controller="Users" asp-action="Index">
                        <span class="pcoded-mtext">Users</span>
                    </a>
                </li>
            }
            @if (User.HasClaim("admin.roles.index"))
            {
                <li>
                    <a asp-controller="Roles" asp-action="Index">
                        <span class="pcoded-mtext">Roles</span>
                    </a>
                </li>
            }
        </ul>
    </div>
</nav>