Bigon.WebUI/Controllers/BlogsController.cs
using Bigon.Business.Modules.BlogPostModule.Commands.BlogPostAddCommentCommand;
using Bigon.Business.Modules.BlogPostModule.Queries.BlogPostGetAllQuery;
using Bigon.Business.Modules.BlogPostModule.Queries.BlogPostGetBySlugQuery;
using Bigon.Business.Modules.BlogPostModule.Queries.BlogPostRecentsQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class BlogsController : Controller
    {
        private readonly IMediator mediator;

        public BlogsController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(BlogPostGetAllRequest request)
        {
            request.OnlyPublished = true;
            var response = await mediator.Send(request);

            var recents = await mediator.Send(new BlogPostRecentsRequest() { Size = 3 });
            ViewBag.Recents = recents;

            return View(response);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("blogs/{slug}")]
        public async Task<IActionResult> Details(BlogPostGetBySlugRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(BlogPostAddCommentRequest request)
        {
            var response = await mediator.Send(request);
            return PartialView("_Comment",response);
            //return Json(response);
        }
    }
}

Bigon.WebUI/Controllers/ShopController.cs
using Bigon.Business.Modules.ShopModule.Commands.BasketAddCommand;
using Bigon.Business.Modules.ShopModule.Commands.BasketChangeQuantityCommand;
using Bigon.Business.Modules.ShopModule.Commands.CreateOrderCommand;
using Bigon.Business.Modules.ShopModule.Commands.RemoveFromBasketCommand;
using Bigon.Business.Modules.ShopModule.Commands.SetRateCommand;
using Bigon.Business.Modules.ShopModule.Queries.BasketListQuery;
using Bigon.Business.Modules.ShopModule.Queries.ComplexFilterQuery;
using Bigon.Business.Modules.ShopModule.Queries.GetPriceQuery;
using Bigon.Business.Modules.ShopModule.Queries.ProductCatalogQuery;
using Bigon.Infrastructure.Extensions;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private readonly IMediator mediator;
        public ShopController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(ComplexFilterRequest request)
        {
            request.Size = request.Size < 16 ? 16 : request.Size;

            var response = await mediator.Send(request);

            if (Request.IsAjaxRequest())
                return PartialView("_Products", response);

            return View(response);
        }

        [AllowAnonymous]
        public async Task<IActionResult> ProductCatalog(ProductCatalogRequest request)
        {
            var response = await mediator.Send(request);

            return PartialView("_ChooseProduct", response);
        }

        [AllowAnonymous]
        [Route("/shop/details/{productId}")]
        public async Task<IActionResult> Details([FromRoute] ProductCatalogRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> GetPrice(GetPriceRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> SetRate(SetRateRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(BasketAddRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(BasketChangeQuantityRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromBasket(RemoveFromBasketRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }

        public async Task<IActionResult> Basket([FromRoute] BasketListRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        public IActionResult Wishlist()
        {
            return View();
        }

        public async Task<IActionResult> Checkout(BasketListRequest request)
        {
            var response = await mediator.Send(request);
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CreateOrderRequest request)
        {
            var response = await mediator.Send(request);
            return Json(response);
        }


    }
}

Bigon.WebUI/Views/Shared/_Navbar.cshtml
<nav>
    <ul class="middle-menu-list">
        <li>
            <a asp-controller="home" asp-action="index">Home</a>
        </li>
        <li>
            <a asp-controller="Shop" asp-action="index">shop</a>
        </li>
        <li>
            <a asp-controller="Blogs" asp-action="index">blog</a>
        </li>
        <li><a asp-controller="Home" asp-action="about">about us</a></li>
        <li><a asp-controller="Home" asp-action="Contact">contact us</a></li>
    </ul>
</nav>

Bigon.WebUI/Views/Shared/_SoftLogin.cshtml
<form class="modal" tabindex="-1" role="dialog" method="post" id="softlogin">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label for="UserName" class="col-sm-2 col-form-label">UserName</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="UserName" name="UserName" placeholder="UserName">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="Password" name="Password" placeholder="Password">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Bagla</button>
                <button type="submit" class="btn btn-primary">Daxil ol</button>
            </div>
        </div>
    </div>
</form>



<script>
    $(document).ready(function(){

        $('form#softlogin').submit(function (e) {
            e.preventDefault();

            let formData = new FormData(e.currentTarget);

            $.ajax({
                url: '@Url.Action("Signin","Account")',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                   $(e.currentTarget).modal('hide');
                },
                error: function (response) {
                    console.log(response);
                }
            });
        });

        $.ajaxSetup({
            statusCode: {
                401: function () {
                    $('#softlogin').modal({ backdrop: 'static', keyboard: false, show: true });
                }
            }
        });
    });
</script>